// Theme registry + NVS-backed current selection.
//
// 4 ink-painting themes ship in V1, all generated by tools/gen_covers.py.
// Palette + cover bundle table here must stay in sync with the
// `THEMES` dict in that script.

#include "theme.h"

#include "../assets/home_covers.h"
#include "../storage/settings.h"

#include "esp_log.h"

#include <algorithm>

namespace pocket {
namespace theme {

namespace {

constexpr const char* TAG    = "THEME";
constexpr const char* NVS_KEY = "theme";

const Theme kThemes[] = {
    {
        .id            = "ink",
        .zh_name       = "水墨",
        .bg_primary    = 0xF0E8D8,
        .bg_elevated   = 0xE6DCC8,
        .ink_primary   = 0x1A1814,
        .ink_secondary = 0x7C7468,
        .accent_main   = 0xA8362E,
        .accent_warn   = 0xA8362E,
        .accent_calm   = 0x3A4A4F,
        .home_covers   = assets::kHomeCoversByTheme[0],
    },
    {
        .id            = "silk",
        .zh_name       = "绢本",
        .bg_primary    = 0xECE6D4,
        .bg_elevated   = 0xDFD7C0,
        .ink_primary   = 0x201E1A,
        .ink_secondary = 0x766E60,
        .accent_main   = 0xA8362E,
        .accent_warn   = 0xA8362E,
        .accent_calm   = 0x3A4A4F,
        .home_covers   = assets::kHomeCoversByTheme[1],
    },
    {
        .id            = "bamboo",
        .zh_name       = "竹简",
        .bg_primary    = 0xD9C9A8,
        .bg_elevated   = 0xCDBD9A,
        .ink_primary   = 0x281C0E,
        .ink_secondary = 0x6C583C,
        .accent_main   = 0xA8362E,
        .accent_warn   = 0xA8362E,
        .accent_calm   = 0x3F4438,
        .home_covers   = assets::kHomeCoversByTheme[2],
    },
    {
        .id            = "stone",
        .zh_name       = "拓片",
        .bg_primary    = 0x2A2D33,
        .bg_elevated   = 0x363941,
        .ink_primary   = 0xE8E4DA,
        .ink_secondary = 0x96928A,
        .accent_main   = 0xC9605A,    // 朱砂 brightened for contrast on dark bg
        .accent_warn   = 0xC9605A,
        .accent_calm   = 0x7C8A92,
        .home_covers   = assets::kHomeCoversByTheme[3],
    },
};
constexpr int kThemeCount = sizeof(kThemes) / sizeof(kThemes[0]);

int s_current = 0;

}  // namespace

int          count()      { return kThemeCount; }
const Theme& at(int idx)  { return kThemes[std::clamp(idx, 0, kThemeCount - 1)]; }

const Theme& current()    { return kThemes[s_current]; }
int          current_idx() { return s_current; }

void load_from_nvs()
{
    uint32_t v = settings::get_u32(NVS_KEY, 0);
    if (v >= static_cast<uint32_t>(kThemeCount)) v = 0;
    s_current = static_cast<int>(v);
    ESP_LOGI(TAG, "loaded theme=%d (%s)", s_current, kThemes[s_current].id);
}

void set_current(int idx)
{
    idx = std::clamp(idx, 0, kThemeCount - 1);
    if (idx == s_current) return;
    s_current = idx;
    settings::set_u32(NVS_KEY, static_cast<uint32_t>(idx));
    ESP_LOGI(TAG, "set theme=%d (%s)", idx, kThemes[idx].id);
}

}  // namespace theme
}  // namespace pocket
