#pragma once

// Pocket Oracle design tokens — runtime-selectable themes.
//
// Each Theme bundles a palette + a 12-entry cover image set. The active
// theme is loaded from NVS on boot (storage::settings key "theme") and
// can be changed via the Settings -> 主题 picker; new theme takes
// effect on the next screen-push (router rebuilds the active app
// after a theme change so the picker landing screen shows the new
// look instantly).
//
// Layout constants and motion constants are theme-independent and
// stay as compile-time constexpr.

#include "lvgl.h"

namespace pocket {
namespace theme {

// ---------- Layout (theme-independent) ----------

constexpr int32_t SCREEN_W = 240;
constexpr int32_t SCREEN_H = 135;

constexpr int32_t SPACE_XS = 4;
constexpr int32_t SPACE_S  = 8;
constexpr int32_t SPACE_M  = 16;
constexpr int32_t SPACE_L  = 24;
constexpr int32_t SPACE_XL = 32;

constexpr int32_t STATUS_BAR_H  = 16;
constexpr int32_t BUTTON_HINT_H = 14;
constexpr int32_t CONTENT_TOP   = STATUS_BAR_H;
constexpr int32_t CONTENT_BOTTOM= SCREEN_H - BUTTON_HINT_H;
constexpr int32_t CONTENT_H     = CONTENT_BOTTOM - CONTENT_TOP;

// ---------- Motion (theme-independent) ----------

constexpr uint32_t ANIM_FAST_MS    = 100;
constexpr uint32_t ANIM_DEFAULT_MS = 300;
constexpr uint32_t ANIM_REVEAL_MS  = 1500;

// ---------- Theme definition ----------

struct Theme {
    const char* id;              // "ink" / "silk" / "bamboo" / "stone"
    const char* zh_name;         // 水墨 / 绢本 / 竹简 / 拓片
    uint32_t bg_primary;
    uint32_t bg_elevated;
    uint32_t ink_primary;
    uint32_t ink_secondary;
    uint32_t accent_main;
    uint32_t accent_warn;
    uint32_t accent_calm;
    bool is_dark;                              // bright bg = false, stone = true
    const lv_image_dsc_t* const* home_covers;  // 12 entries
    const lv_font_t* title_font;               // per-theme brush font (28 px)
    const lv_font_t* display_font;             // per-theme brush font (48 px)
};

// Theme registry — index range [0, count()).
int          count();
const Theme& at(int idx);

// Active theme. current_idx() defaults to 0 (ink) until NVS load runs.
const Theme& current();
int          current_idx();

// Load active theme from NVS. Called once at boot from main. Safe to
// call before LVGL init.
void load_from_nvs();

// Select theme by index; persists to NVS. Out-of-range is silently
// clamped to 0..count()-1.
void set_current(int idx);

// ---------- Color accessors (delegate to current theme) ----------

inline lv_color_t bg_primary()    { return lv_color_hex(current().bg_primary); }
inline lv_color_t bg_elevated()   { return lv_color_hex(current().bg_elevated); }
inline lv_color_t ink_primary()   { return lv_color_hex(current().ink_primary); }
inline lv_color_t ink_secondary() { return lv_color_hex(current().ink_secondary); }
inline lv_color_t accent_main()   { return lv_color_hex(current().accent_main); }
inline lv_color_t accent_warn()   { return lv_color_hex(current().accent_warn); }
inline lv_color_t accent_calm()   { return lv_color_hex(current().accent_calm); }

// ---------- Type ----------

// LXGW WenKai 楷书 — CJK-capable body fonts, subsetted at design time
// to the chars we actually render. Matches the brush aesthetic of the
// home covers without paying for a full GB2312 dictionary.
// (Generated by tools/gen_cjk_font.py.)
extern "C" const lv_font_t lxgw_wenkai_cjk_14;
extern "C" const lv_font_t lxgw_wenkai_cjk_16;

// Per-theme display fonts (48 px) — each theme's signature brush face,
// subsetted by tools/gen_themed_display_fonts.py. Matched in size to
// the original Montserrat display slot so app layouts don't shift.
extern "C" const lv_font_t theme_ink_display_48;
extern "C" const lv_font_t theme_silk_display_48;
extern "C" const lv_font_t theme_bamboo_display_48;
extern "C" const lv_font_t theme_stone_display_48;

// Per-theme title fonts (28 px) — best size to show brush personality
// on multi-character app titles like "抛一枚硬币" / "今日运势".
extern "C" const lv_font_t theme_ink_title_28;
extern "C" const lv_font_t theme_silk_title_28;
extern "C" const lv_font_t theme_bamboo_title_28;
extern "C" const lv_font_t theme_stone_title_28;

inline const lv_font_t* font_body()    { return &lxgw_wenkai_cjk_16; }
inline const lv_font_t* font_caption() { return &lxgw_wenkai_cjk_14; }
inline const lv_font_t* font_title()   { return &lv_font_montserrat_24; }
inline const lv_font_t* font_display() { return &lv_font_montserrat_48; }

// Theme-aware display font. Use for app titles + big result words
// where the brush character is the visual highlight. Body / hint text
// stays on font_body() because grass-script / brush fonts at 16 px are
// near-unreadable.
inline const lv_font_t* font_display_themed() { return current().display_font; }

// Theme-aware title font (28 px) — for the headline strip at the top
// of each app. Multi-character titles read with more brush
// personality at 28 px than the 48 px single big result word.
inline const lv_font_t* font_title_themed()   { return current().title_font; }

// ---------- Ink palette (per-app signature colors) ----------
//
// Each in-app accent color has a value optimized for light-bg themes
// (ink/silk/bamboo) and a brightened twin for the dark stone theme.
// theme::ink_color(c) returns the right one for the current theme.
//
// Apps pick a stable signature color so users learn that color =
// app, while switching theme rotates the brush face + paper bg.

struct InkColor {
    uint32_t on_light;
    uint32_t on_dark;
};

namespace ink {
constexpr InkColor ZHUSHA   = {0xA8362E, 0xE26B62};  // 朱砂 vermilion (印章/警示)
constexpr InkColor QINGMO   = {0x3A4A4F, 0xA0B5BA};  // 青墨 dark cool blue-gray
constexpr InkColor DAILAN   = {0x2C4870, 0x7AA5D2};  // 黛蓝 indigo
constexpr InkColor ZHESHI   = {0x9C6B3C, 0xD8A266};  // 赭石 ochre / earth
constexpr InkColor DAIZI    = {0x5C3B5C, 0xB098B0};  // 黛紫 deep purple
constexpr InkColor LANHUA   = {0x6B5BA0, 0xA89CD0};  // 兰花紫 orchid
constexpr InkColor SONGLV   = {0x4A6B45, 0x8FB78A};  // 松绿 pine green
constexpr InkColor CANGCUI  = {0x447844, 0x7CC07C};  // 苍翠 jade green
constexpr InkColor YUANMO   = {0x5C544A, 0xA8A096};  // 远墨 distant ink
}  // namespace ink

inline uint32_t   ink_color_hex(const InkColor& c) {
    return current().is_dark ? c.on_dark : c.on_light;
}
inline lv_color_t ink_color(const InkColor& c) {
    return lv_color_hex(ink_color_hex(c));
}

// ---------- Legacy hex constants ----------
// Some apps reach into theme:: directly when calling LVGL APIs that
// expect a uint32_t. Provide current-theme'd functions for that use
// case (keeps the call-sites short).
inline uint32_t COLOR_BG_PRIMARY()    { return current().bg_primary; }
inline uint32_t COLOR_BG_ELEVATED()   { return current().bg_elevated; }
inline uint32_t COLOR_INK_PRIMARY()   { return current().ink_primary; }
inline uint32_t COLOR_INK_SECONDARY() { return current().ink_secondary; }
inline uint32_t COLOR_ACCENT_MAIN()   { return current().accent_main; }
inline uint32_t COLOR_ACCENT_WARN()   { return current().accent_warn; }
inline uint32_t COLOR_ACCENT_CALM()   { return current().accent_calm; }

}  // namespace theme
}  // namespace pocket
