#!/usr/bin/env python3
"""Synthesize a short 'wooden fish' percussion sample as int16 PCM.

The real instrument is a hollow wooden block struck with a soft mallet —
a sharp transient ("tok") immediately followed by a tonal body that
decays in ~100 ms. We approximate that with three additive ingredients:

  1. Attack: a 5 ms broadband noise burst with a 1.5 ms exponential decay.
     This is the "tok" — the percussive consonant.
  2. Body: two damped sine waves at the block's fundamental + a fifth
     harmonic-ish (480 / 720 Hz, ratio ~1.5). Real wooden blocks have
     messy inharmonic spectra, but two slightly-detuned sines + the
     noise transient sells the illusion well enough at this volume.
  3. Envelope: exponential decay (~40 ms time constant) over the body
     so the whole hit is gone in ~120 ms.

Output: a C++ header at the relative path passed on the command line
(or stdout if none), with:
    constexpr uint32_t kMuyuPcmSampleRate = ...;
    constexpr int16_t  kMuyuPcm[]         = { ... };

Run once and commit both this script and the generated .h. Re-run only
when you want to tweak the timbre.
"""

import math
import random
import sys

SAMPLE_RATE   = 16000
DURATION_SEC  = 0.20       # 200 ms — let the body ring out longer
ATTACK_SEC    = 0.005      # noise burst length
ATTACK_TAU    = 0.0015     # noise envelope time constant (very fast)
BODY_TAU      = 0.070      # tonal-body envelope time constant (deeper, longer ring)
F1, F2        = 320.0, 480.0   # lower fundamentals = more "wood" less "plastic"
HEADROOM      = 0.98       # final peak / int16 max — push hard so PCM dominates amp hum
COMPRESS_GAIN = 3.0        # soft-clip multiplier: makes the wave "fatter" without
                           # exceeding int16, which raises perceived loudness on the
                           # tiny StickS3 speaker without changing its peak SPL ceiling

random.seed(2026)          # determinism: re-running gives same .h


def synthesize() -> list[int]:
    n = int(SAMPLE_RATE * DURATION_SEC)
    raw: list[float] = []
    for i in range(n):
        t = i / SAMPLE_RATE
        noise = 0.0
        if t < ATTACK_SEC:
            env = math.exp(-t / ATTACK_TAU)
            noise = random.uniform(-1.0, 1.0) * env * 0.6
        body_env = math.exp(-t / BODY_TAU)
        body = (0.55 * math.sin(2 * math.pi * F1 * t)
                + 0.30 * math.sin(2 * math.pi * F2 * t)) * body_env
        raw.append(noise + body)

    # Normalize, then soft-clip via tanh to compress dynamic range —
    # boosts perceived loudness on the tiny StickS3 speaker without
    # changing the peak. (Pure scaling can't add loudness here because
    # we're already at int16 ceiling; compression trades headroom for
    # area under the curve, which is what the ear hears.)
    peak = max(abs(s) for s in raw) or 1.0
    norm = [s / peak for s in raw]
    compressed = [math.tanh(s * COMPRESS_GAIN) for s in norm]
    return [max(-32768, min(32767, int(s * HEADROOM * 32767.0)))
            for s in compressed]


def emit_header(out, samples: list[int]) -> None:
    n = len(samples)
    out.write(f"""#pragma once

// Generated by tools/gen_muyu_pcm.py — do not edit by hand.
// Re-run the script to regenerate after tweaking synthesis params.

#include <cstddef>
#include <cstdint>

namespace pocket {{
namespace audio {{

constexpr uint32_t kMuyuPcmSampleRate = {SAMPLE_RATE};
constexpr std::size_t kMuyuPcmLen     = {n};

constexpr int16_t kMuyuPcm[kMuyuPcmLen] = {{
""")
    cols = 12
    for i in range(0, n, cols):
        chunk = samples[i:i + cols]
        out.write("    " + ", ".join(f"{x:6d}" for x in chunk) + ",\n")
    out.write("};\n\n}  // namespace audio\n}  // namespace pocket\n")


def main() -> None:
    samples = synthesize()
    if len(sys.argv) >= 2:
        with open(sys.argv[1], "w", encoding="utf-8") as f:
            emit_header(f, samples)
        print(f"wrote {sys.argv[1]} ({len(samples)} samples, "
              f"{len(samples) * 2} bytes)", file=sys.stderr)
    else:
        emit_header(sys.stdout, samples)


if __name__ == "__main__":
    main()
