#!/usr/bin/env python3
"""Convert per-theme PNG covers to a single LVGL header.

Layout under the input root:
    covers/
      ink/      cover_NN.png  x12
      silk/     cover_NN.png  x12
      bamboo/   cover_NN.png  x12
      stone/    cover_NN.png  x12

Outputs one C++ header with:
  - kCover<Theme><NN>Data byte arrays (RGB565 little-endian)
  - lv_image_dsc_t for each
  - kHomeCovers<Theme>[12] tables, indexed by home_menu cursor
  - kHomeCoverThemeCount + kHomeCoverThemes[][] master table

Usage:
    png_to_lvgl_img.py <input_root> <output_header.h>
"""

import re
import sys
from pathlib import Path

from PIL import Image

# Theme order = enum order in firmware. Keep aligned with theme.cc.
THEMES = ["ink", "silk", "bamboo", "stone"]


def rgb565_bytes(img: Image.Image) -> bytes:
    img = img.convert("RGB")
    out = bytearray(img.width * img.height * 2)
    px = img.load()
    i = 0
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out[i]     = v & 0xFF
            out[i + 1] = (v >> 8) & 0xFF
            i += 2
    return bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    cols = 16
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(struct_name: str, data_name: str,
             w: int, h: int, data_len: int) -> str:
    return (
        f"const lv_image_dsc_t {struct_name} = {{\n"
        f"    .header = {{\n"
        f"        .magic   = LV_IMAGE_HEADER_MAGIC,\n"
        f"        .cf      = LV_COLOR_FORMAT_RGB565,\n"
        f"        .w       = {w},\n"
        f"        .h       = {h},\n"
        f"        .stride  = {w * 2},\n"
        f"    }},\n"
        f"    .data_size = {data_len},\n"
        f"    .data      = {data_name},\n"
        f"}};\n"
    )


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: png_to_lvgl_img.py <input_root> <output_header.h>",
              file=sys.stderr)
        sys.exit(2)
    root = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    pattern = re.compile(r"^cover_(\d+)\.png$")

    parts = [
        "#pragma once",
        "",
        "// Generated by tools/png_to_lvgl_img.py — do not edit by hand.",
        "// Re-run after editing covers (tools/gen_covers.py).",
        "",
        "#include \"lvgl.h\"",
        "",
        "namespace pocket {",
        "namespace assets {",
        "",
    ]

    theme_count = 0
    total_bytes = 0
    theme_table = []

    for theme_name in THEMES:
        theme_dir = root / theme_name
        if not theme_dir.is_dir():
            print(f"WARN: missing theme dir {theme_dir}", file=sys.stderr)
            continue

        covers = []
        for p in sorted(theme_dir.glob("cover_*.png")):
            m = pattern.match(p.name)
            if m:
                covers.append((int(m.group(1)), p))
        if not covers:
            print(f"WARN: no covers in {theme_dir}", file=sys.stderr)
            continue

        parts.append(f"// ---- theme: {theme_name} ----")
        parts.append("")
        decls = []
        for idx, p in covers:
            img = Image.open(p)
            data = rgb565_bytes(img)
            total_bytes += len(data)
            stem = f"{theme_name.capitalize()}{idx:02d}"
            data_name = f"kCover{stem}Data"
            dsc_name  = f"kCover{stem}"
            parts.append(emit_byte_array(data_name, data))
            parts.append("")
            parts.append(emit_dsc(dsc_name, data_name,
                                  img.width, img.height, len(data)))
            decls.append(dsc_name)

        list_name = f"kHomeCovers{theme_name.capitalize()}"
        parts.append(f"inline const lv_image_dsc_t* "
                     f"{list_name}[{len(decls)}] = {{")
        for n in decls:
            parts.append(f"    &{n},")
        parts.append("};")
        parts.append("")
        theme_table.append((theme_name, list_name, len(decls)))
        theme_count += 1

    if not theme_table:
        sys.exit("no themes rendered; pass a valid <input_root>")

    # All themes must agree on cover count.
    cover_count = theme_table[0][2]
    for name, _, n in theme_table:
        if n != cover_count:
            sys.exit(f"theme {name} has {n} covers; expected {cover_count}")

    parts.append(f"constexpr int kHomeCoverCount = {cover_count};")
    parts.append(f"constexpr int kHomeThemeCount = {theme_count};")
    parts.append("inline const lv_image_dsc_t* const* "
                 "kHomeCoversByTheme[kHomeThemeCount] = {")
    for _, list_name, _ in theme_table:
        parts.append(f"    {list_name},")
    parts.append("};")
    parts.append("")
    parts.append("}  // namespace assets")
    parts.append("}  // namespace pocket")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({theme_count} themes x {cover_count} covers, "
          f"{total_bytes} bytes of pixel data)", file=sys.stderr)


if __name__ == "__main__":
    main()
