#!/usr/bin/env python3
"""Convert PNG covers to LVGL v9 RGB565 image descriptors.

Reads every cover_NN_*.png in the input directory, packs the pixels as
little-endian RGB565 (LVGL's native format on ESP32-S3), and emits one
.h file with all 12 lv_image_dsc_t structs plus a kHomeCovers[] table
indexed 0..11 the way home_menu cursor positions are.

Usage:
    png_to_lvgl_img.py <input_dir> <output_header.h>

Re-run whenever covers/*.png change. The header references LVGL types
so it must live under firmware/main/ and be #include'd after <lvgl.h>.
"""

import re
import sys
from pathlib import Path

from PIL import Image


def rgb565_bytes(img: Image.Image) -> bytes:
    """RGB888 -> little-endian RGB565 bytes, row-major."""
    img = img.convert("RGB")
    out = bytearray(img.width * img.height * 2)
    px = img.load()
    i = 0
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out[i]     = v & 0xFF        # low byte first (little-endian)
            out[i + 1] = (v >> 8) & 0xFF
            i += 2
    return bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    cols = 16
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(struct_name: str, data_name: str,
             w: int, h: int, data_len: int) -> str:
    return (
        f"const lv_image_dsc_t {struct_name} = {{\n"
        f"    .header = {{\n"
        f"        .magic   = LV_IMAGE_HEADER_MAGIC,\n"
        f"        .cf      = LV_COLOR_FORMAT_RGB565,\n"
        f"        .w       = {w},\n"
        f"        .h       = {h},\n"
        f"        .stride  = {w * 2},\n"
        f"    }},\n"
        f"    .data_size = {data_len},\n"
        f"    .data      = {data_name},\n"
        f"}};\n"
    )


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: png_to_lvgl_img.py <input_dir> <output_header.h>",
              file=sys.stderr)
        sys.exit(2)

    in_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    pattern = re.compile(r"^cover_(\d+)_.*\.png$")
    covers = []
    for p in sorted(in_dir.glob("cover_*.png")):
        m = pattern.match(p.name)
        if not m:
            continue
        idx = int(m.group(1))
        covers.append((idx, p))
    if not covers:
        sys.exit("no cover_NN_*.png found in " + str(in_dir))

    parts = [
        "#pragma once",
        "",
        "// Generated by tools/png_to_lvgl_img.py — do not edit by hand.",
        "// Re-run after editing covers (tools/gen_covers.py).",
        "",
        "#include \"lvgl.h\"",
        "",
        "namespace pocket {",
        "namespace assets {",
        "",
    ]

    decls = []
    for idx, p in covers:
        img = Image.open(p)
        data = rgb565_bytes(img)
        data_name = f"kCover{idx:02d}Data"
        dsc_name = f"kCover{idx:02d}"
        parts.append(emit_byte_array(data_name, data))
        parts.append("")
        parts.append(emit_dsc(dsc_name, data_name, img.width, img.height, len(data)))
        decls.append(dsc_name)

    parts.append("// Cursor index -> cover, matching home_menu kEntries order.")
    parts.append(f"constexpr int kHomeCoverCount = {len(decls)};")
    parts.append("inline const lv_image_dsc_t* kHomeCovers[kHomeCoverCount] = {")
    for n in decls:
        parts.append(f"    &{n},")
    parts.append("};")
    parts.append("")
    parts.append("}  // namespace assets")
    parts.append("}  // namespace pocket")

    text = "\n".join(parts) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    total = sum(len(rgb565_bytes(Image.open(p))) for _, p in covers)
    print(f"wrote {out_path} ({len(covers)} covers, {total} bytes of pixel data)",
          file=sys.stderr)


if __name__ == "__main__":
    main()
